import type { Metadata } from "next";
import { Roboto, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ClerkProvider } from "@clerk/nextjs";
import { localization } from "@/lib/utils";
import { ChildProps } from "@/types";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Udemy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};

interface Props extends ChildProps {
  params: { locale: string };
}

export default async function Layout(props: Props) {
  const { children, params } = props;
  const { locale } = await params;

  const messages = await getMessages();
  const local = localization(locale);
  return (
    <ClerkProvider
      localization={local}
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html suppressHydrationWarning lang={locale} className="no-scrollbar">
        <body
          suppressHydrationWarning
          className={`${roboto.variable} ${spaceGrotesk.variable} antialiased`}
        >
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main>{children}</main>
              <Toaster />
            </ThemeProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
