import type { Metadata } from "next";
import { Roboto, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import AppNavbar from "@/components/layout/AppNavbar";
import { ClerkProvider } from "@clerk/nextjs";
import { localization } from "@/lib/utils";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Udemy",
  description: "Generated by create next app",
  icons: {
    icon: "https://www.logoai.com/oss/icons/2021/12/02/u8tXD2V7rro6bok.png",
  },
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();
  const local = localization(locale);
  return (
    <ClerkProvider localization={local} >
      <html lang={locale} suppressHydrationWarning>
        <body
          suppressHydrationWarning
          className={`${roboto.variable} ${spaceGrotesk.variable} antialiased`}
        >
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <AppNavbar />
              <main className="mt-20">{children}</main>
            </ThemeProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
